config/routes.rb
FinTech::Application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'team' => 'home#team'
  get 'contact' => 'home#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/home/about.html.erb
<% @page_title = "About Us" %>

	<div class="wide_content">
		<div class="body">
			<p class="title_text">
				About Foundation View Capital 
			</p>
			<p class="body_text">
				Foundation View Capital Management, LLC is an indirect majority owned subsidiary of Institutional Financial Markets, Inc. (“IFMI”).  IFMI is a NYSE MKT listed financial services company specializing in fixed income markets.  IFMI was founded in 1999 as an investment firm focused on small-cap banking institutions, but has grown to provide an expanding range of asset management and capital markets services.
			</p>
			<p class="body_text">
				IFMI’s asset management business manages assets primarily through investment funds, managed accounts and collateralized debt obligations.  IFMI’s capital markets business consists of fixed income sales, trading, and financing as well as new issue placements in corporate and securitized products, and advisory services, operating primarily through IFMI’s subsidiaries, J.V.B. Financial Group, LLC (<%= link_to 'www.jvbfinancial.com', "https://www.jvbfinancial.com", :target => '_blank' %>) in the United States and Cohen & Company Financial Limited (<%= link_to 'www.cohenandcompany.com', "http://www.cohenandcompany.com", :target => '_blank' %>) in Europe.
			</p>
		</div>
	</div>

app/views/home/contact.html.erb
<% @page_title = "Contact Us" %>

	<div class="wide_content">
		<div class="body">
			<p class="title_text">
				Contact Information   
			</p>
			<p class="city_text">
				Contact Us
			</p>
			<p class="address_text">
				Email: <%= mail_to "info@foundationviewcapital.com" %>
			</p>
			<p class="address_spacing_text">
				Phone: (646) 495-7473
			</p>
			<p class="city_text">
				New York Office
			</p>
			<p class="address_text">
				712 Fifth Avenue
			</p>
			<p class="address_text">
				Floor 8
			</p>
			<p class="address_text">
				New York, NY 10019
			</p>
		</div>
	</div>

app/views/home/index.html.erb
<% @page_title = "Home" %>

	<div class="wide_content">
		<div class="body">
			<p class="title_text">
				Foundation View Capital Management
			</p>
			<p class="body_text">
				Foundation View Capital Management, LLC ("Foundation View Capital") is a New York-based alternative asset manager, focused on Collateralized Loan Obligations ("CLOs") and special opportunities in structured credit products.
			</p>
			<p class="body_text">	
				Our primary investment objective is to generate high current income; our secondary objective is to generate capital appreciation.
			</p>
			<p class="body_text">
				Foundation View Capital Management uses a differentiating investment approach that is driven by a combination of careful manager selection, active participation in the origination process, and optimization of various structural features to benefit our investors.
			</p>
		</div>
	</div>

app/views/home/team.html.erb
<% @page_title = "Our Team" %>

	<div class="wide_content">
		<div class="body">
			<p class="title_text">
				Our Team 
			</p>

			<p class="position_text"></p>





			<% if false %>
			<p class="avatar">
				<%= image_tag("MAvatar.png") %>
			</p>
			<span class="daniel_name_text" tabindex="0">
				Daniel G. Cohen
			</span>
			<p class="position_text">
				CEO | Principal
			</p>
			<p class="daniel_body_text">
				Daniel G. Cohen currently serves as Executive Chairman of TheBancorp, Inc. and as Vice Chairman for Institutional Financial Markets Inc. (formerly known as Cohen & Company). Mr. Cohen previously served as Chairman and Chief Executive Officer. Mr. Cohen has also served as Chief Executive, Chairman or a board member of various subsidiaries and related entities.  Mr. Cohen also served as the Chief Executive Officer of FinTech Acquisition Corp, which recently acquired CardConnect.  In these capacities he has overseen the financing, acquisition and placement of billions of dollars of FinTech related assets.  Mr. Cohen is a member of the Academy of the University of Pennsylvania, a member of the Visiting Committees for the Humanities of the University of Chicago, and a member of the board for the Paris Center of Columbia University.  Mr. Cohen is also the Chairman of the Board of the Paideia Institute, which promotes Classical Studies, and a Trustee of the Arete Foundation.

			</p>
			<p class="avatar">
				<%= image_tag("MAvatar.png") %>
			</p>
			<p class="plamen_name_text" tabindex="0">
				Plamen Mitrikov
			</p>
			<p class="position_text">
				Portfolio Manager | Principal
			</p>
			<p class="plamen_body_text">
				Plamen Mitrikov has spent his entire career in structured credit. Prior to establishing Foundation View Capital, Mr. Mitrikov was an Executive Director in Morgan Stanley’s New Issue CLO group, responsible for all aspects of CLO structuring and execution. Mr. Mitrikov specialized in bringing to market newer CLO platforms, and also spent considerable time analyzing and marketing CLO equity. Prior to Morgan Stanley, Mr. Mitrikov served as Co-Head of Structured Credit at Princeridge, where he was in charge of CLO new issue, and ABS/Trust Preferred CDO trading. From 2006 to 2011, Mr. Mitrikov served as an Executive Vice President of RAIT Investment Trust, a Philadelphia headquartered commercial real estate mortgage REIT. From April 2003 to February 2006, Mr. Mitrikov held various positions, including that of Vice President and Director, in the structured credit products group at Merrill Lynch specializing in the origination and execution of Trust Preferred and ABS CDOs. Prior to joining Merrill Lynch, Mr. Mitrikov worked in the new issue CDO group at Credit Suisse First Boston.
			</p>
			<% end %>




			<div id = "box" tabindex="0"> 
			<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Plamen Mitrikov </div>
  				<div id="position">Principal</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Plamen Mitrikov is a co-founding Principal and Lead Portfolio Manager of Foundation View Capital. Mr. Mitrikov has spent his entire career in structured credit. Prior to co-founding Foundation View Capital Management, Mr. Mitrikov was a deal leader in Morgan Stanley’s New Issue CLO group and was responsible for all aspects of CLO structuring and execution. Mr. Mitrikov specialized in bringing to market newer CLO management platforms, and was also actively involved in analyzing and marketing CLO equity. Prior to Morgan Stanley, Mr. Mitrikov served as Co-Head of the ABS and Special Situations group at IFMI, where he was responsible for new issue securitizations and secondary trading of trust preferred and ABS collateralized debt obligations. Prior to IFMI, Mr. Mitrikov served as an Executive Vice President of RAIT Investment Trust, a Philadelphia-headquartered commercial real estate mortgage real estate investment trust. From April 2003 to February 2006, Mr. Mitrikov held various positions, including that of Vice President and Director, in the structured credit products group at Merrill Lynch, specializing in the origination and execution of trust preferred and ABS collateralized debt obligations. Prior to joining Merrill Lynch, Mr. Mitrikov worked in the new issue collateral debt obligation group at Credit Suisse First Boston. Mr. Mitrikov holds an M.Sc. in Industrial Engineering and Operations Research from Columbia University and a B.A in Economics and Physics from Franklin and Marshall College.  
  				</div>
			</div>
			
			<div id = "box" tabindex="0"> 
  				<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Daniel Cohen </div>
  				<div id="position">Principal</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Daniel G. Cohen is a co-founding Principal of Foundation View Capital Management. He also currently serves as Executive Chairman of The Bancorp, Inc., Vice Chairman for IFMI and a Chief Executive Officer of FinTech Acquisition Corp II. In these capacities, Mr. Cohen has overseen the financing, acquisition and placement of billions of dollars of ABS, CMBS, corporate and financial technology related assets. Mr. Cohen is a member of the Academy of the University of Pennsylvania, a member of the Visiting Committees for the Humanities of the University of Chicago, and a member of the board for the Paris Center of Columbia University. Mr. Cohen is also the Chairman of the Board of the Paideia Institute, which promotes classical studies, and a Trustee of the Arete Foundation. Mr. Cohen holds a B.A. in East Asian History from University of Chicago.  
  				</div>
  			</div>

  			<div id = "box" tabindex="0"> 
  				<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Lester Brafman </div>
  				<div id="position">CEO of IFMI</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Lester Brafman is Chief Executive Officer of IFMI and of J.V.B. Financial Group, LLC, IFMI’s majority-owned broker-dealer subsidiary. Prior to joining IFMI, during an 11-year tenure at Goldman Sachs, Mr. Brafman served as Chief Operating Officer of Credit and Mortgage Trading and as Head of High Yield and Distressed Trading. Prior to joining Goldman Sachs in 2001, Mr. Brafman spent over six years at Credit Suisse First Boston, holding numerous positions, including Head of High Yield Trading and Head of Emerging Market and Sovereign Trading. Mr. Brafman also spent several years at Wasserstein Perella & Co. and Lehman Brothers. Mr. Brafman received a B.A. from Columbia University and an M.B.A. from the Amos Tuck School of Business Administration, Dartmouth College.
  				</div>
  			</div>

			<div id = "box" tabindex="0"> 
  				<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Andrew K. Davilman </div>
  				<div id="position">COO</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Andrew K. Davilman is the COO of Foundation View Capital Management. He also serves as a Managing Director of IFMI’s Asset Management business and as a Managing Director, Sales and Special Projects with J.V.B. Financial Group, LLC, IFMI’s broker-dealer subsidiary. Mr. Davilman spent 16 years at Goldman, Sachs & Co. in a variety of positions. As a Managing Director, from 2006 to 2010, Mr. Davilman founded and co-ran the Structured Credit Sales desk. Before that Mr. Davilman worked in Institutional Mortgage sales from 1998 to 2006. From 1994 to 1998, Mr. Davilman traded MBS derivatives including Inverse Floaters, Inverse IOs, IOs and POs, and CMO Residuals. Before joining Goldman, Sachs, Mr. Davilman traded MBS derivatives at Lehman Brothers from 1989 to 1995. Mr. Davilman has expertise in credit default swaps, collateralized debt obligations and collateralized loan obligations, as well as other derivatives and cash instruments typically traded across the fixed income universe. Mr. Davilman holds an A.B. in Religion from Dartmouth College and holds an M.B.A from Stanford University’s Graduate School of Business.  
  				</div>
  			</div>

  			<div id = "box" tabindex="0"> 
  				<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Joseph W. Pooler </div>
  				<div id="position">CFO</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Joseph W. Pooler serves as a Chief Financial Officer of Foundation Capital Management. Mr. Pooler has served as Executive Vice President, Chief Financial Officer and Treasurer of IFMI since 2009 and as IFMI, LLC’s Chief Financial Officer since November 2007 and as its Chief Administrative Officer since May 2007. From July 2006 through November 2007, Mr. Pooler also served as Senior Vice President of Finance of IFMI, LLC. From November 2007 through March 2009, Mr. Pooler served as Chief Financial Officer of Muni Funding Company of America, LLC, a company managed by IFMI, LLC that invested in middle-market non-profit organizations. Prior to joining IFMI, LLC, from 1999 through 2005, Mr. Pooler held key management positions at Pegasus Communications Corporation (now known as Xanadoo Company), which operated in the direct broadcast satellite television and broadcast television station segments. While at Pegasus, Mr. Pooler held various positions including Chief Financial Officer, Principal Accounting Officer, and Senior Vice President of Finance. From 1993 through 1999, Mr. Pooler held various management positions with MEDIQ, Incorporated, including Corporate Controller, Director of Operations, and Director of Sales Support. Mr. Pooler holds a B.A. from Ursinus College and an M.B.A. from Drexel University.  
  				</div>
  			</div>

			<div id = "box" tabindex="0"> 
  				<% if false %>
  				<div id = "circle"> </div>
  			<% end %>
  				<div id = "name" > Steven Ezzes </div>
  				<div id="position">Managing Director</div>
  				<div id = "box2" tabindex="1"></div>
  				<div id = "bio"> 
  					Steven Ezzes is a Managing Director of Fountain View Capital Management. Mr. Ezzes joined Fountain View from Mariner Investment Group where he was a member of the fund of funds investment committee and the business development group. Prior to joining Mariner, Mr. Ezzes was a Partner and portfolio manager at Airlie Opportunity Fund where he managed high yield portfolios and CLO's. For a number of years Mr. Ezzes was a Partner at Bass Investment Limited Partnership created by Richard Rainwater from the Bass Brothers organization. Early in his career Mr. Ezzes was one of the original members of the Goldman, Sachs High Yield Group where he was responsible for Capital Markets and Distribution. Mr. Ezzes has served on the boards of a number of US and Australian companies.
  				</div>
  			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <title>Foundation View | <%= @page_title || "application" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>


</head>

	<%= render(:partial => "shared/header")%>

<body>

<%= yield %>

</body>

<% if false %>
<div class="footer">
Foundation View Capital | 712 Fifth Avenue, Floor 8, New York, NY 10019
</div>
<% end %>

</html>

app/views/shared/_header.html.erb
<header class="desktop">

	<div><%= link_to(image_tag("fvclogo2.png"), main_app.root_url, :class => 'icon_header') %></div>

	<div class="header_text">
		<ul>
			<li><%= link_to(image_tag("AboutUs.png", :onMouseover => "src='/assets/AboutUsa-e6eae8a154e178b105d2f367ac442e97.png';", :onMouseout => "src='/assets/AboutUs-59f1f4bbac152dd0ed905b516b4b94de.png';"), about_path, :class => 'about_us_header') %></li>
			<li><%= link_to(image_tag("OurTeam.png", :onMouseover => "src='/assets/OurTeama-ee4b28e557dd80d8f034ebbe0fc993ef.png';", :onMouseout => "src='/assets/OurTeam-adc3106dd04517361e802524612c238c.png';"), team_path, :class => 'our_team_header') %></li>
			<li><%= link_to(image_tag("ContactUs.png", :onMouseover => "src='/assets/ContactUsa-c32003a802edfb935555ce241b6c89af.png';", :onMouseout => "src='/assets/ContactUs-62546176b6ca2b15bfba83b5f07e9d0c.png';"), contact_path, :class => 'contact_us_header') %></li> 
		</ul>
	</div>
</header>